jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  application:
    name: localens
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 700877174115-rj4ba7komte6a6d7v8vpk7m2qfckm83s.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          kakao:
            client-id: 1f7bbaf4c63d1a4afc3500d868f7c1b8
            client-authentication-method: none
            redirect-uri: "http://localhost:8080/auth/login/kakao"
          naver:
            client-id: ZhIoK6i2zzDd0DnUxYDn
            client-secret: ZhIoK6i2zzDd0DnUxYDn
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"

influxdb:
#  url: http://3.106.193.43:8086
#  token: HieAKTvkj-RdQyxiHn4-Z2BdwrhVLe9XFB-bbQLY1rnBEXfGvNb9SJQ7RIDEqREm7bzHovw00Dv8pCZm6a6Xwg==
  url: http://localhost:8086
  token: LTjZTx3BsfI7BfKl7-AaYwR_DZwR3pUu_tlJ15499qXFJvuSwcq70WH3D2pVnk1YgrjK6GvUZ_3Bx6-cY9k6cQ==
#  org: localens
  org: dev
  bucket: result_bucket

