jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  application:
    name: localens
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:mysql:localens.cpc8gqku4ew1.ap-northeast-2.rds.amazonaws.com:3306/localens
    username: localens
    password: localens
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

influxdb:
  url: http://3.34.131.242:8086
  token: 75XnM_QleVAocbDl0vpX-IYdaTiJiwkBZ42CjC0kzQCYaPOKDIdoVTOj-boTrYRZJz_6mtO64P5LT6VJM6TPXg==
  org: dev
  bucket: hourly
  measurement: visitor_data

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true