jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  application:
    name: localens
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 700877174115-rj4ba7komte6a6d7v8vpk7m2qfckm83s.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          kakao:
            client-id: 1f7bbaf4c63d1a4afc3500d868f7c1b8
            client-authentication-method: none
            redirect-uri: "http://localhost:8080/auth/login/kakao"
          naver:
            client-id: ZhIoK6i2zzDd0DnUxYDn
            client-secret: ZhIoK6i2zzDd0DnUxYDn
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"

influxdb:
  url: http://3.34.131.242:8086
  token: 75XnM_QleVAocbDl0vpX-IYdaTiJiwkBZ42CjC0kzQCYaPOKDIdoVTOj-boTrYRZJz_6mtO64P5LT6VJM6TPXg==
  org: dev
  bucket: hourly
  measurement: visitor_data

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true